name: MLPerf automotive submission checker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install mlcflow
        mlc pull repo mlcommons@mlperf-automations
    - name: Run MLPerf Automotive Submission Checker
      run: |
        mlcr run,submission,checker,_wg-automotive --adr.automotive-src.tags=_branch.master --env.MLC_MLPERF_SUBMISSION_CHECKER_VERSION=v0.5 --quiet --extra_args=" --skip-extra-files-in-root-check" --submission_dir=./