name: MLPerf Automotive results updater


on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install mlc-scripts

    - name: Run MLPerf Automotive Submission Checker and generate results summary
      run: |
        mlcr run,submission,checker,_wg-automotive --adr.automotive-src.tags=_branch.master --quiet --env.MLC_MLPERF_SUBMISSION_CHECKER_VERSION=v0.5 --extra_args=" --skip-extra-files-in-root-check"  --submission_dir=./ > >(tee -a out.txt) 2> >(tee -a checker_log.txt >&2)
        mlcr convert,from-csv,to-md --csv_file=summary.csv --md_file=README.md

        USER="mlcommons-bot"
        EMAIL="mlcommons-bot@users.noreply.github.com"

        git config --global user.name "$USER"
        git config --global user.email "$EMAIL"
        git add summary*
        echo -e 'Please download [summary.xlsx](summary.xlsx) to view the most recent results. \n ```' > temp
        tail -n 16 checker_log.txt >> temp
        echo -e '\n```\n' >> temp
        cat temp | cat - README.md > temp1
        head -n 100 temp1 > README.md
        git add README.md
        
        git diff --quiet HEAD -- summary.csv summary.json summary_results.json || (git commit -am "Updated results summary" && git push)
